name-template: "v$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
# version-template: "$MAJOR.$MINOR.$PATCH"
categories:
  - title: "🚀 Features"
    labels:
      - "Type: Feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "Type: Bug"
  - title: "🧰 Maintenance"
    labels:
      - "Type: Chore"
change-title-escapes: '\<*_&'
exclude-labels:
  - "exclude from changelog"
autolabeler:
  - label: "Type: Chore"
    title:
      - "/chore/i"
  - label: "Type: Bug"
    title:
      - "/fix/i"
  - label: "Type: Feature"
    title:
      - '/feat\/.+/'
template: |
  ## Changes

  $CHANGES
