name: uzu_flavored_markdown
description: A Markdown renderer for Flutter. Create rich text output,
  including text styles, tables, links, and more, from plain text data
  formatted with simple Markdown tags.
repository: https://github.com/uzuPJ/uzu_flavored_markdown
issue_tracker: https://github.com/uzuPJ/uzu_flavored_markdown/issues
version: 0.0.19

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  assets:
    - lib/assets/blank.png

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  markdown: ^4.0.0
  meta: ^1.3.0
  path: ^1.8.0
  url_launcher: ^6.0.9
  photo_view: ^0.12.0
  cached_network_image: ^3.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
