name: Publish package to pub.dev

on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  update-pubspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
      - run: echo $NEW_VERSION
      - id: update-script
        run: |
          NEW_VERSION=${TAGNAME:1}
          echo $NEW_VERSION
          sed -r -i -e "s/version: [0-9]+\.[0-9]+\.[0-9]+/version: $NEW_VERSION/" pubspec.yaml
        env:
          TAGNAME: ${{ github.event.release.tag_name }}
      - run: cat pubspec.yaml
      - name: Update proto file
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          branch: main
          commit_message: Update proto file

  publish:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    needs: update-pubspec
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.FLUTTER_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.FLUTTER_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1576508276459
          }
          EOF

      # -f: Publish without confirmation if there are no errors.
      - name: Publish
        run: |
          pub publish -f
