name: Publish package to pub.dev

on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.FLUTTER_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.FLUTTER_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1576508276459
          }
          EOF

      # -f: Publish without confirmation if there are no errors.
      - name: Publish
        run: |
          pub publish -f
